# Generated by Django 5.1.dev20231208072151 on 2026-02-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
