# Generated by Django 5.1.dev20231208072151 on 2026-02-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
